version: "3.3"
services: 
    proxy:
        image: mitmproxy/mitmproxy:4.0.1
        volumes: 
            - ${PWD}/plugins:/home/mitmproxy/plugins
            - ${PWD}/certs:/home/mitmproxy/.mitmproxy
            - ${PWD}/entrypoint.sh:/usr/local/bin/entrypoint.sh
        ports: 
            - "8080:8080"
            - "8081:8081"
        command: >
            sh -c "chmod +x /usr/local/bin/entrypoint.sh &&
            /usr/local/bin/entrypoint.sh"